# Generated by Django 5.0.7 on 2024-08-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_alliance_portal', '0003_bursar_title_staffs_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='school_reopening_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
