# Generated by Django 5.0.7 on 2024-08-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_alliance_portal', '0004_schoolsettings_school_reopening_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='plain_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
