# Generated by Django 5.0.7 on 2024-08-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_alliance_portal', '0005_students_plain_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='promotion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
