# Generated by Django 5.0.7 on 2024-08-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_alliance_portal', '0006_students_promotion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='arrears_entered',
            field=models.BooleanField(default=False),
        ),
    ]
